[build]
  command = "npm run build"
  publish = "dist/portfolio-website/browser"

[functions]
  directory = "dist/portfolio-website/server"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200